version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging into AWS ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 605134454693.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t nginx-app .
      - docker tag nginx-app:latest 605134454693.dkr.ecr.us-east-1.amazonaws.com/nginx-app:latest
  post_build:
    commands:
      - echo "Pushing the image to AWS ECR..."
      - docker push 605134454693.dkr.ecr.us-east-1.amazonaws.com/nginx-app:latest
      - echo "Build completed successfully!"
artifacts:
  files:
    - "**/*"
